### ISSUE TITLE
Using the lowerbound

### ISSUE THREAD

**Issue by jcheyns** [evanfields/TravelingSalesmanHeuristics.jl#15]
Question, why not use the lowerbound in the sequence of heuristics to stop when a solution would be found with a cost=lowerbound?

**Comment by evanfields** [comment]
That's a fair question. The lower bounds available are almost never tight. That is, except on super tiny toy instances, the lower bounds are lower than the optimal cost. By definition, the heuristics costs are at least as large as the optimal cost. So the only case where a heuristic-derived path cost would equal the lower bound is a tiny instance where simple path generation heuristics are finding the true optimal cost in microseconds anyway.

At least, I think. If you want to open a PR or can find a nontrivial example where using the available lower bounds to short-circuit the sequence of heuristics, I'd be super interested!
